theme: jekyll-theme-slate
title: Fundamentals of inference and learning, EE-411
description : A Set of Lectures given at EPFL in 2021 by Prof. Florent Krzakala 
logo : Screenshot 2019-03-18 at 16.26.19.png	
